### ISSUE TITLE
Issues on 2.6.4

### ISSUE THREAD

**Issue by Assasinowy** [szumielxd/TuSKe#7]
[14:22:52] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Skript v2.6.4
--
1263 | java.lang.NullPointerException: null
1264 | at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:?]
1265 | at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:?]
1266 | at com.github.tukenuke.tuske.util.VariableUtil.pasteVariables(VariableUtil.java:59) ~[?:?]
1267 | at com.github.tukenuke.tuske.sections.gui.EffMakeGUI.lambda$execute$0(EffMakeGUI.java:79) ~[?:?]
1268 | at com.github.tukenuke.tuske.manager.gui.v2.GUIInventory$1.onClick(GUIInventory.java:215) ~[?:?]
1269 | at com.github.tukenuke.tuske.listeners.GUIListener.onEvent(GUIListener.java:57) ~[?:?]
1270 | at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.check(SkriptGUIEvent.java:53) ~[?:?]
1271 | at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:136) ~[?:?]
1272 | at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[?:?]
1273 | at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[?:?]
1274 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
1275 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
1276 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
1277 | at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.12.2.jar:git-Paper-1620]
1278 | at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1620]
1279 | at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1620]
1280 | at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
1281 | at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
1282 | at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
1283 | at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
1284 | at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
1285 | at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
1286 | at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
1287 | at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
1288 | at java.lang.Thread.run(Unknown Source) [?:?]

Yeah, it doesn't work and I don't think that it's something on my side

**Comment by szumielxd** [comment]
https://github.com/szumielxd/TuSKe/commit/46c94d2f59bf06f504530ee6baa23db0a44c7001
